{% set version = '0.0.5.9001' %}
{% set commit = "025e0a36d84a1b879eb68d4f27ea1211403ec9e9" %}

package:
  name: r-obistools
  version: {{ version }}

source:
  fn: obistools_{{ version }}.zip
  url: https://github.com/iobis/obistools/archive/{{ commit }}.zip
  sha256: fccdbd00c95236408235bd55a785e96f5a7345da0aed8562412943a232ff0c90

build:
  number: 0
  skip: True  # [win]
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-cowplot
    - r-data.tree
    - r-digest
    - r-dplyr
    - r-geosphere
    - r-ggplot2
    - r-httr
    - r-jsonlite
    - r-leaflet
    - r-raster
    - r-rgdal
    - r-rgeos
    - r-rmarkdown
    - r-sf
    - r-sp
    - r-stringr
    - r-tidyr
    - r-worrms
    - r-xml2
    - r-rappdirs
    - r-maps
    - r-knitr
  run:
    - r-base
    - r-cowplot
    - r-data.tree
    - r-digest
    - r-dplyr
    - r-geosphere
    - r-ggplot2
    - r-httr
    - r-jsonlite
    - r-leaflet
    - r-raster
    - r-rgdal
    - r-rgeos
    - r-rmarkdown
    - r-sf
    - r-sp
    - r-stringr
    - r-tidyr
    - r-worrms
    - r-xml2
    - r-rappdirs
    - r-maps
    - r-knitr

test:
  commands:
    - $R -e "library('obistools')"  # [not win]
    - "\"%R%\" -e \"library('obistools')\""  # [win]

about:
  home: https://github.com/iobis/obistools
  license: MIT
  license_file: LICENSE
  summary: Data Enhancement and Quality Control of Marine Species Observations

extra:
  recipe-maintainers:
    - ocefpaf
