travis:
  secure:
    BINSTAR_TOKEN: JjFrDjUY2ek0mZy+Xre5CxCv7RixYfvie+1zvQiSJ+12COExSad1WxcwRQbeBzUe3s41c6GsgwMJqpYMlHk4dMAlKhHypa9iq0rhdC6ry/qBGePHoNBfVNF5TcHop7iAsnMpCcypzM3oyQRvVkvqiOLzQ2BRzs/x37A0V7RTB2elC3TUftoPcvZlh2HamMuZlVITAF02uHFp+kiewsHE74bEP1082mK2LbESIU/ttLwnOtwZsF34Wk0/vgHVY2knS59vnjJUigRqgNmr3rTVzGKkjbIWyu6pjdYNxlZ57WJ5q0WmMAIOXaIM4AJfGLQ2R3KO+sFDXQn2xXo7PSAEQkduVUG43SoP8mPqFEeDdLrAsVE2euCPzWKLtB8Pr/XX+Tg6Vaqh6JXKnUNMD10Xdm7ef3byTBTcuBZ6VpI8oo4X131+QAbio2lRHElHMghlTHygbpMFT9HUwDOFqlFgBSS3HhzoN0G79EIwp+8a3YvUbe0TBYi/PmxKmvIawaatl+zp2cN+w380iEO4qDLBUz1qn01ZZwRwj/E8Ytw2JP9U9tn/vxiDj5br/kFanEF+nCAeyM5Jp7B1CZTPlwpHzQuqfiTLYL++MxqX0hIWJL1u9XXB+dfcg1oE9jXRmRwnRDT9od96AFU8Gk0EBdxSCwkSwxT4eNLcC8XgUKTmcfA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
